name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: soham1027
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate GitHub Stats & Streak SVGs
        run: |
          mkdir -p dist
          curl -L "https://github-readme-stats.vercel.app/api?username=Soham1027&show_icons=true&theme=tokyonight&count_private=true" -o dist/github-stats.svg
          curl -L "https://github-readme-streak-stats.herokuapp.com/?user=Soham1027&theme=tokyonight" -o dist/github-streak.svg

      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
